gesdinet_jwt_refresh_token:
    # Используем стандартную сущность из бандла
    ttl: 2592000 # 30 days
    token_parameter_name: refreshToken
    firewall: api
    user_identity_field: id
    refresh_token_class: App\Identity\Infrastructure\Entity\RefreshToken
    doctrine_mappings: false
